//go:build ignore

// Regenerate with: go run scripts/contracts/runtime_business_package_inventory.go
package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

const (
	runtimeRoot = "runtime"
	serviceRoot = "runtime/bootstrap/composition"
	outputPath  = "runtime/boundary/testdata/runtime-domain-package-migration-inventory.md"
)

type sourceFile struct {
	path string
	file *ast.File
	raw  []byte
}

func main() {
	check := flag.Bool("check", false, "fail when the generated inventory is stale")
	flag.Parse()

	serviceFiles := parseProductionFiles(serviceRoot)
	businessFiles := parseProductionFiles("runtime/domain")
	content := renderInventory(serviceFiles, businessFiles)
	if *check {
		current, err := os.ReadFile(outputPath)
		if err != nil {
			panic(err)
		}
		if !bytes.Equal(current, content) {
			fmt.Fprintf(os.Stderr, "%s is stale; run go run scripts/contracts/runtime_business_package_inventory.go\n", outputPath)
			os.Exit(1)
		}
		return
	}
	if err := os.WriteFile(outputPath, content, 0o644); err != nil {
		panic(err)
	}
}

func renderInventory(serviceFiles, businessFiles map[string]sourceFile) []byte {
	var out bytes.Buffer
	fmt.Fprintln(&out, "# Runtime Business Package Migration Inventory")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "> Generated by `go run scripts/contracts/runtime_business_package_inventory.go`. Do not edit by hand.")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "Service source fingerprint: `%x`\n\n", fingerprint(serviceFiles))

	fmt.Fprintln(&out, "## Current Runtime package roots")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "| Root | Production Go files | Test Go files |")
	fmt.Fprintln(&out, "|---|---:|---:|")
	for _, row := range runtimePackageCounts() {
		fmt.Fprintf(&out, "| `%s` | %d | %d |\n", row.name, row.production, row.tests)
	}

	candidates := classifyCandidates(serviceFiles)
	fmt.Fprintln(&out, "\n## Service file ownership candidates")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "Classification is filename-based discovery only. A candidate is not safe to move until its private-symbol crossings and SCC are reviewed.")
	for _, owner := range sortedMapKeys(candidates) {
		fmt.Fprintf(&out, "\n### %s (%d)\n\n", owner, len(candidates[owner]))
		for _, path := range candidates[owner] {
			fmt.Fprintf(&out, "- `%s`\n", path)
		}
	}

	fmt.Fprintln(&out, "\n## Current no-logic boundary blockers")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "These production imports cross from `domain/*` into concrete `infrastructure/*` packages. They are retained only because this migration may not redesign ports or application services.")
	blockers := infrastructureImportEdges(businessFiles)
	if len(blockers) == 0 {
		fmt.Fprintln(&out, "\nNone.")
	} else {
		for _, blocker := range blockers {
			fmt.Fprintf(&out, "- `%s`\n", blocker)
		}
	}

	edges := privateDependencyEdges(serviceFiles)
	fmt.Fprintln(&out, "\n## Same-package private dependency edges")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "These edges are conservative AST evidence: the source file references an unexported package declaration or method name defined in another service file.")
	if len(edges) == 0 {
		fmt.Fprintln(&out, "\nNone.")
	} else {
		for _, from := range sortedMapKeys(edges) {
			for _, to := range sortedSetKeys(edges[from]) {
				fmt.Fprintf(&out, "- `%s` -> `%s`\n", from, to)
			}
		}
	}

	receiverEdges := receiverCoLocationEdges(serviceFiles)
	fmt.Fprintln(&out, "\n## Method receiver co-location edges")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "Go requires a method and its receiver base type to remain in the same package. These edges supplement private-symbol analysis for package-only moves.")
	if len(receiverEdges) == 0 {
		fmt.Fprintln(&out, "\nNone.")
	} else {
		for _, from := range sortedMapKeys(receiverEdges) {
			for _, to := range sortedSetKeys(receiverEdges[from]) {
				fmt.Fprintf(&out, "- `%s` -> `%s`\n", from, to)
			}
		}
	}

	fmt.Fprintln(&out, "\n## Package-move closure groups")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "Private-symbol and method-receiver edges are treated as undirected because either direction requires both files to remain in one Go package unless code structure or visibility changes.")
	for index, group := range packageMoveClosureGroups(serviceFiles, edges, receiverEdges) {
		fmt.Fprintf(&out, "\n- Move closure %d: %d files (%s).\n", index+1, len(group), closureOwnerSummary(group))
	}

	fmt.Fprintln(&out, "\n## Strongly connected file groups")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "Each group below is an indivisible move unit under the current no-logic-refactor constraint.")
	groups := stronglyConnectedGroups(serviceFiles, edges)
	if len(groups) == 0 {
		fmt.Fprintln(&out, "\nNo multi-file SCCs detected.")
	} else {
		for index, group := range groups {
			fmt.Fprintf(&out, "\n### SCC %d (%d files)\n\n", index+1, len(group))
			for _, path := range group {
				fmt.Fprintf(&out, "- `%s`\n", path)
			}
		}
	}
	return out.Bytes()
}

func receiverCoLocationEdges(files map[string]sourceFile) map[string]map[string]bool {
	typeOwners := map[string]map[string]bool{}
	for path, source := range files {
		for _, declaration := range source.file.Decls {
			general, ok := declaration.(*ast.GenDecl)
			if !ok || general.Tok != token.TYPE {
				continue
			}
			for _, spec := range general.Specs {
				if item, ok := spec.(*ast.TypeSpec); ok {
					addDefinition(typeOwners, item.Name.Name, path)
				}
			}
		}
	}
	edges := map[string]map[string]bool{}
	for from, source := range files {
		for _, declaration := range source.file.Decls {
			method, ok := declaration.(*ast.FuncDecl)
			if !ok || method.Recv == nil || len(method.Recv.List) == 0 {
				continue
			}
			name := receiverBaseName(method.Recv.List[0].Type)
			for to := range typeOwners[name] {
				if to == from {
					continue
				}
				if edges[from] == nil {
					edges[from] = map[string]bool{}
				}
				edges[from][to] = true
			}
		}
	}
	return edges
}

func receiverBaseName(expression ast.Expr) string {
	switch value := expression.(type) {
	case *ast.Ident:
		return value.Name
	case *ast.StarExpr:
		return receiverBaseName(value.X)
	case *ast.IndexExpr:
		return receiverBaseName(value.X)
	case *ast.IndexListExpr:
		return receiverBaseName(value.X)
	default:
		return ""
	}
}

func packageMoveClosureGroups(files map[string]sourceFile, edgeSets ...map[string]map[string]bool) [][]string {
	adjacency := map[string]map[string]bool{}
	for path := range files {
		adjacency[path] = map[string]bool{}
	}
	for _, edges := range edgeSets {
		for from, targets := range edges {
			for to := range targets {
				if _, ok := files[from]; !ok {
					continue
				}
				if _, ok := files[to]; !ok {
					continue
				}
				adjacency[from][to] = true
				adjacency[to][from] = true
			}
		}
	}
	visited := map[string]bool{}
	groups := [][]string{}
	for _, start := range sortedMapKeys(files) {
		if visited[start] {
			continue
		}
		visited[start] = true
		stack := []string{start}
		group := []string{}
		for len(stack) > 0 {
			last := len(stack) - 1
			node := stack[last]
			stack = stack[:last]
			group = append(group, node)
			for _, next := range sortedSetKeys(adjacency[node]) {
				if !visited[next] {
					visited[next] = true
					stack = append(stack, next)
				}
			}
		}
		sort.Strings(group)
		groups = append(groups, group)
	}
	sort.Slice(groups, func(i, j int) bool {
		if len(groups[i]) != len(groups[j]) {
			return len(groups[i]) > len(groups[j])
		}
		return groups[i][0] < groups[j][0]
	})
	return groups
}

func closureOwnerSummary(group []string) string {
	counts := map[string]int{}
	for _, path := range group {
		counts[candidateOwner(strings.TrimSuffix(filepath.Base(path), ".go"))]++
	}
	parts := make([]string, 0, len(counts))
	for _, owner := range sortedMapKeys(counts) {
		parts = append(parts, fmt.Sprintf("%s=%d", owner, counts[owner]))
	}
	return strings.Join(parts, ", ")
}

func infrastructureImportEdges(files map[string]sourceFile) []string {
	const prefix = "github.com/domainry/domainry-runtime/runtime/infrastructure/"
	edges := []string{}
	for path, source := range files {
		for _, spec := range source.file.Imports {
			importPath := strings.Trim(spec.Path.Value, `"`)
			if strings.HasPrefix(importPath, prefix) {
				edges = append(edges, path+" -> "+importPath)
			}
		}
	}
	sort.Strings(edges)
	return edges
}

type packageCount struct {
	name              string
	production, tests int
}

func runtimePackageCounts() []packageCount {
	counts := map[string]*packageCount{}
	entries, err := os.ReadDir(runtimeRoot)
	if err != nil {
		panic(err)
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		name := filepath.Join(runtimeRoot, entry.Name())
		row := &packageCount{name: name}
		err := filepath.WalkDir(name, func(path string, item os.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if item.IsDir() || !strings.HasSuffix(path, ".go") {
				return nil
			}
			if strings.HasSuffix(path, "_test.go") {
				row.tests++
			} else {
				row.production++
			}
			return nil
		})
		if err != nil {
			panic(err)
		}
		counts[name] = row
	}
	rows := make([]packageCount, 0, len(counts))
	for _, row := range counts {
		rows = append(rows, *row)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].name < rows[j].name })
	return rows
}

func parseProductionFiles(root string) map[string]sourceFile {
	files := map[string]sourceFile{}
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		parsed, err := parser.ParseFile(token.NewFileSet(), path, raw, 0)
		if err != nil {
			return err
		}
		files[filepath.ToSlash(path)] = sourceFile{path: filepath.ToSlash(path), file: parsed, raw: raw}
		return nil
	})
	if err != nil {
		panic(err)
	}
	return files
}

func fingerprint(files map[string]sourceFile) [32]byte {
	hash := sha256.New()
	for _, path := range sortedMapKeys(files) {
		hash.Write([]byte(path))
		hash.Write([]byte{0})
		hash.Write(files[path].raw)
		hash.Write([]byte{0})
	}
	var result [32]byte
	copy(result[:], hash.Sum(nil))
	return result
}

func classifyCandidates(files map[string]sourceFile) map[string][]string {
	result := map[string][]string{}
	for path := range files {
		name := strings.TrimSuffix(filepath.Base(path), ".go")
		owner := candidateOwner(name)
		result[owner] = append(result[owner], path)
	}
	for owner := range result {
		sort.Strings(result[owner])
	}
	return result
}

func candidateOwner(name string) string {
	for _, technicalPrefix := range []string{"adapter_", "orchestration_", "projection_", "validation_"} {
		if strings.HasPrefix(name, technicalPrefix) {
			return candidateOwner(strings.TrimPrefix(name, technicalPrefix))
		}
	}
	rules := []struct {
		owner    string
		prefixes []string
	}{
		{"agent", []string{"agent_"}},
		{"audit", []string{"audit_"}},
		{"identity", []string{"auth", "identity_", "principal_"}},
		{"automation", []string{"automation_", "record_automation"}},
		{"workflow", []string{"workflow_", "record_workflow"}},
		{"scheduler", []string{"scheduler_", "record_scheduler"}},
		{"integration", []string{"integration_", "record_integration"}},
		{"changeplan", []string{"business_change_plan", "business_reference", "business_system"}},
		{"action", []string{"business_action", "record_action", "record_object_action"}},
		{"pipeline", []string{"pipeline_"}},
		{"deployment", []string{"runtime_status"}},
		{"metadata", []string{"metadata_", "schema_", "record_metadata", "record_schema", "record_dictionar", "record_localized"}},
		{"record", []string{"record_", "record"}},
		{"capability", []string{"authoring_", "execution_capability"}},
	}
	for _, rule := range rules {
		for _, prefix := range rule.prefixes {
			if strings.HasPrefix(name, prefix) {
				return rule.owner
			}
		}
	}
	return "unclassified"
}

func privateDependencyEdges(files map[string]sourceFile) map[string]map[string]bool {
	definitions := map[string]map[string]bool{}
	for path, source := range files {
		for _, declaration := range source.file.Decls {
			switch value := declaration.(type) {
			case *ast.FuncDecl:
				if isPrivate(value.Name.Name) {
					addDefinition(definitions, value.Name.Name, path)
				}
			case *ast.GenDecl:
				for _, spec := range value.Specs {
					switch item := spec.(type) {
					case *ast.TypeSpec:
						if isPrivate(item.Name.Name) {
							addDefinition(definitions, item.Name.Name, path)
						}
					case *ast.ValueSpec:
						for _, name := range item.Names {
							if isPrivate(name.Name) {
								addDefinition(definitions, name.Name, path)
							}
						}
					}
				}
			}
		}
	}
	edges := map[string]map[string]bool{}
	for from, source := range files {
		ast.Inspect(source.file, func(node ast.Node) bool {
			var name string
			switch value := node.(type) {
			case *ast.Ident:
				name = value.Name
			case *ast.SelectorExpr:
				name = value.Sel.Name
			}
			for to := range definitions[name] {
				if to != from {
					if edges[from] == nil {
						edges[from] = map[string]bool{}
					}
					edges[from][to] = true
				}
			}
			return true
		})
	}
	return edges
}

func addDefinition(definitions map[string]map[string]bool, name, path string) {
	if definitions[name] == nil {
		definitions[name] = map[string]bool{}
	}
	definitions[name][path] = true
}

func isPrivate(name string) bool {
	if name == "" || name == "_" {
		return false
	}
	first, _ := utf8FirstRune(name)
	return unicode.IsLower(first)
}

func utf8FirstRune(value string) (rune, int) {
	for _, item := range value {
		return item, len(string(item))
	}
	return 0, 0
}

func stronglyConnectedGroups(files map[string]sourceFile, edges map[string]map[string]bool) [][]string {
	index := 0
	indices := map[string]int{}
	lowlink := map[string]int{}
	onStack := map[string]bool{}
	stack := []string{}
	groups := [][]string{}
	var visit func(string)
	visit = func(node string) {
		indices[node] = index
		lowlink[node] = index
		index++
		stack = append(stack, node)
		onStack[node] = true
		for _, next := range sortedSetKeys(edges[node]) {
			if _, seen := indices[next]; !seen {
				visit(next)
				if lowlink[next] < lowlink[node] {
					lowlink[node] = lowlink[next]
				}
			} else if onStack[next] && indices[next] < lowlink[node] {
				lowlink[node] = indices[next]
			}
		}
		if lowlink[node] != indices[node] {
			return
		}
		group := []string{}
		for {
			last := stack[len(stack)-1]
			stack = stack[:len(stack)-1]
			onStack[last] = false
			group = append(group, last)
			if last == node {
				break
			}
		}
		if len(group) > 1 {
			sort.Strings(group)
			groups = append(groups, group)
		}
	}
	for _, path := range sortedMapKeys(files) {
		if _, seen := indices[path]; !seen {
			visit(path)
		}
	}
	sort.Slice(groups, func(i, j int) bool {
		if len(groups[i]) != len(groups[j]) {
			return len(groups[i]) > len(groups[j])
		}
		return groups[i][0] < groups[j][0]
	})
	return groups
}

func sortedMapKeys[T any](values map[string]T) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedSetKeys(values map[string]bool) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
