package contract

// Runtime Operations is the source owner for these cross-layer Action keys.
// Every key is also its exact role Permission key.
const (
	ActionListOperations                 = "runtime.operations.list_operations"
	ActionGetOperation                   = "runtime.operations.get_operation"
	ActionOperationCatalog               = "runtime.operations.operation_catalog"
	ActionListControls                   = "runtime.operations.list_controls"
	ActionListBreakGlass                 = "runtime.operations.list_break_glass"
	ActionListIdempotencyReceipts        = "runtime.operations.receipts"
	ActionOperationRunbook               = "runtime.operations.operation_runbook"
	ActionSetControl                     = "runtime.operations.set_control"
	ActionInspectDeadLetter              = "runtime.operations.inspect_dead_letter"
	ActionResolveDeadLetter              = "runtime.operations.resolve_dead_letter"
	ActionRetryDeadLetter                = "runtime.operations.retry_dead_letter"
	ActionAcknowledgeDeadLetter          = "runtime.operations.acknowledge_dead_letter"
	ActionRetryIdempotencyReceipt        = "runtime.operations.retry"
	ActionResetIdempotencyReceipt        = "runtime.operations.reset"
	ActionCreateBackup                   = "runtime.operations.create_backup"
	ActionRestoreBackup                  = "runtime.operations.restore_backup"
	ActionDeleteWorkspace                = "runtime.operations.delete_workspace"
	ActionEnableMaintenance              = "runtime.operations.enable_maintenance"
	ActionDisableMaintenance             = "runtime.operations.disable_maintenance"
	ActionPauseWorkerOwner               = "runtime.operations.pause_worker_owner"
	ActionResumeWorkerOwner              = "runtime.operations.resume_worker_owner"
	ActionDrainRuntimeInstance           = "runtime.operations.drain_runtime_instance"
	ActionUndrainRuntimeInstance         = "runtime.operations.undrain_runtime_instance"
	ActionForceReleaseLease              = "runtime.operations.force_release_lease"
	ActionDryRunBulkDeadLetters          = "runtime.operations.dry_run_bulk_dead_letters"
	ActionApplyBulkDeadLetters           = "runtime.operations.apply_bulk_dead_letters"
	ActionCaptureDiagnostics             = "runtime.operations.capture_diagnostics"
	ActionEnableBreakGlass               = "runtime.operations.enable_break_glass"
	ActionDisableBreakGlass              = "runtime.operations.disable_break_glass"
	ActionEnableAutomationRule           = "runtime.operations.enable_automation_rule"
	ActionDisableAutomationRule          = "runtime.operations.disable_automation_rule"
	ActionRetryIntegrationEvent          = "runtime.operations.retry_integration_event"
	ActionReplayIntegrationEvent         = "runtime.operations.replay_integration_event"
	ActionRetryRuntimePublication        = "runtime.operations.retry_runtime_publication"
	ActionReconcileIntegrationInvocation = "runtime.operations.reconcile_integration_invocation"
	ActionRunLifecycleCleanupJob         = "runtime.operations.run_lifecycle_cleanup_job"
)
