package notifications

import "net/http"

func (h *NotificationsHandler) RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /business/notifications", h.authenticated(h.listInbox))
	mux.HandleFunc("GET /business/notifications/facets", h.authenticated(h.inboxFacets))
	mux.HandleFunc("GET /business/notifications/unread-count", h.authenticated(h.inboxUnreadCount))
	mux.HandleFunc("GET /business/notifications/stream", h.authenticated(h.streamInbox))
	mux.HandleFunc("GET /business/notification-preferences", h.authenticated(h.getMyNotificationPreference))
	mux.HandleFunc("PUT /business/notification-preferences", h.authenticated(h.saveMyNotificationPreference))
	mux.HandleFunc("GET /business/notifications/saved-views", h.authenticated(h.listInboxSavedViews))
	mux.HandleFunc("GET /business/notifications/delegations", h.authenticated(h.listInboxDelegations))
	mux.HandleFunc("PUT /business/notifications/delegations/{delegationID}", h.authenticated(h.saveInboxDelegation))
	mux.HandleFunc("DELETE /business/notifications/delegations/{delegationID}", h.authenticated(h.deleteInboxDelegation))
	mux.HandleFunc("GET /business/notifications/delegated-owners", h.authenticated(h.listDelegatedInboxOwners))
	mux.HandleFunc("PUT /business/notifications/saved-views/{viewKey}", h.authenticated(h.saveInboxSavedView))
	mux.HandleFunc("DELETE /business/notifications/saved-views/{viewKey}", h.authenticated(h.deleteInboxSavedView))
	mux.HandleFunc("GET /business/notifications/{notificationID}", h.authenticated(h.getInboxItem))
	mux.HandleFunc("GET /business/notifications/{notificationID}/actions/{actionKey}/resolve", h.authenticated(h.resolveInboxAction))
	mux.HandleFunc("POST /business/notifications/{notificationID}/read", h.authenticated(h.readInboxItem))
	mux.HandleFunc("POST /business/notifications/{notificationID}/unread", h.authenticated(h.unreadInboxItem))
	mux.HandleFunc("POST /business/notifications/{notificationID}/archive", h.authenticated(h.archiveInboxItem))
	mux.HandleFunc("POST /business/notifications/{notificationID}/restore", h.authenticated(h.restoreInboxItem))
	mux.HandleFunc("POST /business/notifications/{notificationID}/acknowledge", h.authenticated(h.acknowledgeInboxAlert))
	mux.HandleFunc("POST /business/notifications/read-all", h.authenticated(h.readAllInboxItems))
	mux.HandleFunc("GET /portal/notifications", h.authenticated(h.listInbox))
	mux.HandleFunc("GET /portal/notifications/facets", h.authenticated(h.inboxFacets))
	mux.HandleFunc("GET /portal/notifications/unread-count", h.authenticated(h.inboxUnreadCount))
	mux.HandleFunc("GET /portal/notifications/stream", h.authenticated(h.streamInbox))
	mux.HandleFunc("GET /portal/notification-preferences", h.authenticated(h.getMyNotificationPreference))
	mux.HandleFunc("PUT /portal/notification-preferences", h.authenticated(h.saveMyNotificationPreference))
	mux.HandleFunc("GET /portal/notifications/saved-views", h.authenticated(h.listInboxSavedViews))
	mux.HandleFunc("GET /portal/notifications/delegations", h.authenticated(h.listInboxDelegations))
	mux.HandleFunc("PUT /portal/notifications/delegations/{delegationID}", h.authenticated(h.saveInboxDelegation))
	mux.HandleFunc("DELETE /portal/notifications/delegations/{delegationID}", h.authenticated(h.deleteInboxDelegation))
	mux.HandleFunc("GET /portal/notifications/delegated-owners", h.authenticated(h.listDelegatedInboxOwners))
	mux.HandleFunc("PUT /portal/notifications/saved-views/{viewKey}", h.authenticated(h.saveInboxSavedView))
	mux.HandleFunc("DELETE /portal/notifications/saved-views/{viewKey}", h.authenticated(h.deleteInboxSavedView))
	mux.HandleFunc("GET /portal/notifications/{notificationID}", h.authenticated(h.getInboxItem))
	mux.HandleFunc("GET /portal/notifications/{notificationID}/actions/{actionKey}/resolve", h.authenticated(h.resolveInboxAction))
	mux.HandleFunc("POST /portal/notifications/{notificationID}/read", h.authenticated(h.readInboxItem))
	mux.HandleFunc("POST /portal/notifications/{notificationID}/unread", h.authenticated(h.unreadInboxItem))
	mux.HandleFunc("POST /portal/notifications/{notificationID}/archive", h.authenticated(h.archiveInboxItem))
	mux.HandleFunc("POST /portal/notifications/{notificationID}/restore", h.authenticated(h.restoreInboxItem))
	mux.HandleFunc("POST /portal/notifications/{notificationID}/acknowledge", h.authenticated(h.acknowledgeInboxAlert))
	mux.HandleFunc("POST /portal/notifications/read-all", h.authenticated(h.readAllInboxItems))
	mux.HandleFunc("GET /notifications/deliveries", h.authenticated(h.listDeliveries))
}
