package notificationmodel

import notificationcontract "github.com/domainry/domainry-notification-sdk/contract"

type NotificationTemplateRecord = notificationcontract.NotificationTemplateRecord
type NotificationTemplateVersion = notificationcontract.NotificationTemplateVersion
type NotificationPublicationRequest = notificationcontract.NotificationPublicationRequest
type NotificationPublicationTransition = notificationcontract.NotificationPublicationTransition
type NotificationDeliveryPolicy = notificationcontract.NotificationDeliveryPolicy
type NotificationRecipientPreference = notificationcontract.NotificationRecipientPreference
type NotificationDeliveryReservation = notificationcontract.NotificationDeliveryReservation
type NotificationDeliveryEvaluationRequest = notificationcontract.NotificationDeliveryEvaluationRequest
type NotificationDeliveryDecision = notificationcontract.NotificationDeliveryDecision
