package notificationmodel

import notificationcontract "github.com/domainry/domainry-notification-sdk/contract"

type NotificationTemplateCapability = notificationcontract.NotificationTemplateCapability
type NotificationTemplate = notificationcontract.NotificationTemplate
type NotificationFallback = notificationcontract.NotificationFallback
type NotificationTemplateVariable = notificationcontract.NotificationTemplateVariable
type NotificationTemplateContent = notificationcontract.NotificationTemplateContent
type NotificationProviderTemplate = notificationcontract.NotificationProviderTemplate
type NotificationProviderTemplateComponent = notificationcontract.NotificationProviderTemplateComponent
type NotificationTemplateFact = notificationcontract.NotificationTemplateFact
type NotificationTemplateAction = notificationcontract.NotificationTemplateAction
type RenderedNotification = notificationcontract.RenderedNotification
