package notificationmodel

import notificationcontract "github.com/domainry/domainry-notification-sdk/contract"

type NotificationEventType = notificationcontract.NotificationEventType
type NotificationInboxEventTypeContent = notificationcontract.NotificationInboxEventTypeContent
type NotificationIntent = notificationcontract.NotificationIntent
type NotificationRule = notificationcontract.NotificationRule
type NotificationRuleChannel = notificationcontract.NotificationRuleChannel
type NotificationGovernanceCatalog = notificationcontract.NotificationGovernanceCatalog
type NotificationInboxAggregate = notificationcontract.NotificationInboxAggregate
type NotificationInboxGovernanceMetrics = notificationcontract.NotificationInboxGovernanceMetrics
type NotificationEventFailureAggregate = notificationcontract.NotificationEventFailureAggregate
type NotificationEventFailureMetrics = notificationcontract.NotificationEventFailureMetrics
