package schema

import "context"

func EnsureEvidenceSchema(ctx context.Context, s Store) error {
	text := s.ApplicationSchemaIDColumnType()
	types := s.RuntimeProfile().EvidenceSchemaTypes(text)
	idempotencyScopeText := types.IdempotencyScope
	retirementEngineText, retirementNamespaceText, retirementKindText, retirementObjectText := types.RetirementEngine, types.RetirementNamespace, types.RetirementKind, types.RetirementObject
	tables := map[string][]string{
		"_release_cohorts": {
			"cohort_key " + text + " PRIMARY KEY",
			"combination_sha256 " + text + " NOT NULL DEFAULT ''",
			"identity_json TEXT NOT NULL DEFAULT ''",
			"generation BIGINT NOT NULL DEFAULT 0",
			"revision BIGINT NOT NULL DEFAULT 0",
			"updated_at " + text + " NOT NULL DEFAULT ''",
		},
		"_release_instances": {
			"instance_id " + text + " PRIMARY KEY",
			"combination_sha256 " + text + " NOT NULL",
			"generation BIGINT NOT NULL",
			"lease_expires_at " + text + " NOT NULL",
			"joined_at " + text + " NOT NULL",
			"heartbeat_at " + text + " NOT NULL",
		},
		"_workflow_executions": {
			"workspace_id " + idempotencyScopeText + " NOT NULL",
			"id " + text + " NOT NULL",
			"workflow_key " + text + " NOT NULL",
			"name TEXT NOT NULL",
			"trigger " + text + " NOT NULL",
			"status " + text + " NOT NULL",
			"action_type " + text,
			"action_json TEXT NOT NULL",
			"payload_json TEXT NOT NULL",
			"result_json TEXT NOT NULL",
			"process_id " + text,
			"node_id " + text,
			"object_key " + text,
			"record_id " + text,
			"actor_id " + text,
			"run_as " + text,
			"idempotency_key " + text,
			"attempt INTEGER NOT NULL DEFAULT 0",
			"max_attempts INTEGER NOT NULL DEFAULT 0",
			"next_run_at " + text,
			"last_error TEXT",
			"lease_owner " + text + " NOT NULL DEFAULT ''",
			"lease_expires_at " + text + " NOT NULL DEFAULT ''",
			"fencing_token BIGINT NOT NULL DEFAULT 0",
			"message TEXT",
			"created_at " + text + " NOT NULL",
			"updated_at " + text + " NOT NULL",
		},
		"_workflow_execution_receipts": {
			"id " + text + " PRIMARY KEY",
			"workspace_id " + idempotencyScopeText + " NOT NULL",
			"workflow_key " + idempotencyScopeText + " NOT NULL",
			"idempotency_key " + idempotencyScopeText + " NOT NULL",
			"request_fingerprint " + text + " NOT NULL",
			"status " + text + " NOT NULL",
			"execution_id " + text + " NOT NULL DEFAULT ''",
			"lease_owner " + text + " NOT NULL",
			"lease_expires_at " + text + " NOT NULL",
			"fencing_token BIGINT NOT NULL DEFAULT 1",
			"created_at " + text + " NOT NULL",
			"updated_at " + text + " NOT NULL",
			"expires_at " + text + " NOT NULL DEFAULT ''",
		},
		"_action_executions": {
			"id " + text + " PRIMARY KEY",
			"workspace_id " + idempotencyScopeText + " NOT NULL",
			"object_key " + idempotencyScopeText + " NOT NULL",
			"record_id " + idempotencyScopeText,
			"action_key " + idempotencyScopeText + " NOT NULL",
			"idempotency_key " + idempotencyScopeText + " NOT NULL",
			"request_fingerprint " + text + " NOT NULL DEFAULT ''",
			"status " + text + " NOT NULL",
			"result_json TEXT NOT NULL",
			"lease_owner " + text + " NOT NULL DEFAULT ''",
			"lease_expires_at " + text + " NOT NULL DEFAULT ''",
			"fencing_token BIGINT NOT NULL DEFAULT 0",
			"response_status INTEGER NOT NULL DEFAULT 0",
			"error_code " + text + " NOT NULL DEFAULT ''",
			"expires_at " + text + " NOT NULL DEFAULT ''",
			"actor_id " + text,
			"role_key " + text,
			"created_at " + text + " NOT NULL",
			"updated_at " + text + " NOT NULL",
		},
		"_action_assurance_grants": {
			"id " + text + " PRIMARY KEY",
			"token_hash " + text + " NOT NULL",
			"workspace_id " + idempotencyScopeText + " NOT NULL",
			"user_id " + idempotencyScopeText + " NOT NULL",
			"action_key " + idempotencyScopeText + " NOT NULL",
			"object_key " + idempotencyScopeText + " NOT NULL",
			"record_id " + idempotencyScopeText + " NOT NULL DEFAULT ''",
			"payload_digest " + text + " NOT NULL",
			"methods_json TEXT NOT NULL",
			"approval_version " + text + " NOT NULL DEFAULT ''",
			"approval_hash " + text + " NOT NULL DEFAULT ''",
			"issued_at " + text + " NOT NULL",
			"expires_at " + text + " NOT NULL",
			"consumed_at " + text + " NOT NULL DEFAULT ''",
		},
		"_record_mutation_executions": {
			"id " + text + " PRIMARY KEY",
			"workspace_id " + idempotencyScopeText + " NOT NULL",
			"operation " + idempotencyScopeText + " NOT NULL",
			"object_key " + idempotencyScopeText + " NOT NULL",
			"target_id " + idempotencyScopeText + " NOT NULL DEFAULT ''",
			"idempotency_key " + idempotencyScopeText + " NOT NULL",
			"request_fingerprint " + text + " NOT NULL",
			"status " + text + " NOT NULL",
			"result_json TEXT NOT NULL",
			"lease_owner " + text + " NOT NULL",
			"lease_expires_at " + text + " NOT NULL",
			"fencing_token BIGINT NOT NULL DEFAULT 1",
			"response_status INTEGER NOT NULL DEFAULT 0",
			"error_code " + text + " NOT NULL DEFAULT ''",
			"expires_at " + text + " NOT NULL DEFAULT ''",
			"actor_id " + text + " NOT NULL DEFAULT ''",
			"created_at " + text + " NOT NULL",
			"updated_at " + text + " NOT NULL",
		},
		"_worker_queue_scopes": {
			"id " + text + " PRIMARY KEY",
			"queue_kind " + idempotencyScopeText + " NOT NULL",
			"scope_key " + idempotencyScopeText + " NOT NULL",
			"updated_at " + text + " NOT NULL",
		},
		"_idempotency_cleanup_leases": {
			"id " + text + " PRIMARY KEY",
			"lease_owner " + text + " NOT NULL DEFAULT ''",
			"lease_expires_at " + text + " NOT NULL DEFAULT ''",
			"fencing_token BIGINT NOT NULL DEFAULT 0",
			"last_started_at " + text + " NOT NULL DEFAULT ''",
			"last_completed_at " + text + " NOT NULL DEFAULT ''",
			"last_deleted INTEGER NOT NULL DEFAULT 0",
			"last_error TEXT NOT NULL DEFAULT ''",
			"updated_at " + text + " NOT NULL DEFAULT ''",
		},
		"_operation_requests": {
			"id " + text + " PRIMARY KEY",
			"workspace_id " + idempotencyScopeText + " NOT NULL",
			"system_purpose " + idempotencyScopeText + " NOT NULL DEFAULT ''",
			"kind " + idempotencyScopeText + " NOT NULL",
			"action_key " + text + " NOT NULL",
			"resource_type " + text + " NOT NULL",
			"resource_id " + text + " NOT NULL DEFAULT ''",
			"idempotency_key " + idempotencyScopeText + " NOT NULL",
			"request_fingerprint " + text + " NOT NULL",
			"requested_by " + text + " NOT NULL",
			"reason TEXT NOT NULL",
			"reference " + text + " NOT NULL DEFAULT ''",
			"status " + text + " NOT NULL",
			"status_url TEXT NOT NULL",
			"result_json TEXT NOT NULL",
			"error_code " + text + " NOT NULL DEFAULT ''",
			"failure_class " + text + " NOT NULL DEFAULT ''",
			"next_action TEXT NOT NULL DEFAULT ''",
			"related_ids_json TEXT NOT NULL",
			"correlation " + text + " NOT NULL DEFAULT ''",
			"evidence_json TEXT NOT NULL",
			"created_at " + text + " NOT NULL",
			"started_at " + text + " NOT NULL DEFAULT ''",
			"finished_at " + text + " NOT NULL DEFAULT ''",
			"updated_at " + text + " NOT NULL",
		},
		"_operation_controls": {
			"system_purpose " + idempotencyScopeText + " NOT NULL",
			"control_kind " + idempotencyScopeText + " NOT NULL",
			"owner " + idempotencyScopeText + " NOT NULL",
			"state " + text + " NOT NULL",
			"reason TEXT NOT NULL",
			"reference " + text + " NOT NULL DEFAULT ''",
			"updated_by " + text + " NOT NULL",
			"revision BIGINT NOT NULL",
			"updated_at " + text + " NOT NULL",
		},
		"_operation_break_glass_grants": {
			"id " + text + " PRIMARY KEY",
			"workspace_id " + idempotencyScopeText + " NOT NULL",
			"state " + text + " NOT NULL",
			"actor_id " + text + " NOT NULL",
			"approver_ids_json TEXT NOT NULL",
			"reason TEXT NOT NULL",
			"incident_ref " + text + " NOT NULL",
			"alert_target " + text + " NOT NULL",
			"audit_event_id " + text + " NOT NULL",
			"expires_at " + text + " NOT NULL",
			"revision BIGINT NOT NULL",
			"created_at " + text + " NOT NULL",
			"updated_at " + text + " NOT NULL",
			"revoked_at " + text + " NOT NULL DEFAULT ''",
			"revoked_by " + text + " NOT NULL DEFAULT ''",
			"revocation_note TEXT NOT NULL DEFAULT ''",
		},
		"_operation_database_retirements": {
			"id " + text + " PRIMARY KEY",
			"engine " + retirementEngineText + " NOT NULL",
			"database_name " + retirementNamespaceText + " NOT NULL",
			"schema_name " + retirementNamespaceText + " NOT NULL DEFAULT ''",
			"object_kind " + retirementKindText + " NOT NULL",
			"object_name " + retirementObjectText + " NOT NULL",
			"parent_name " + retirementObjectText + " NOT NULL DEFAULT ''",
			"owner " + text + " NOT NULL",
			"state " + text + " NOT NULL",
			"blocked_reason TEXT NOT NULL DEFAULT ''",
			"read_count BIGINT NOT NULL DEFAULT 0",
			"write_count BIGINT NOT NULL DEFAULT 0",
			"last_read_at " + text + " NOT NULL DEFAULT ''",
			"last_write_at " + text + " NOT NULL DEFAULT ''",
			"source_counts_json TEXT NOT NULL DEFAULT '{}'",
			"retirement_json TEXT NOT NULL",
			"updated_at " + text + " NOT NULL",
		},
		"_automation_rule_executions": {
			"id " + text + " PRIMARY KEY",
			"workspace_id " + text + " NOT NULL",
			"rule_key " + text + " NOT NULL",
			"object_key " + text + " NOT NULL",
			"record_id " + text,
			"phase " + text + " NOT NULL",
			"operation " + text + " NOT NULL",
			"status " + text + " NOT NULL",
			"actor_id " + text,
			"role_key " + text,
			"request_id " + text,
			"correlation_id " + text,
			"event_id " + text,
			"duration_ms INTEGER NOT NULL DEFAULT 0",
			"error_code " + text,
			"candidate_json TEXT NOT NULL",
			"trace_json TEXT NOT NULL",
			"created_at " + text + " NOT NULL",
			"updated_at " + text + " NOT NULL",
		},
		"_automation_instruction_executions": {
			"id " + text + " PRIMARY KEY",
			"workspace_id " + text + " NOT NULL",
			"idempotency_key " + text + " NOT NULL",
			"rule_key " + text + " NOT NULL",
			"object_key " + text + " NOT NULL",
			"record_id " + text + " NOT NULL",
			"record_version " + text + " NOT NULL",
			"operation " + text + " NOT NULL",
			"instruction_key " + text + " NOT NULL",
			"status " + text + " NOT NULL",
			"result_json TEXT NOT NULL",
			"error_code " + text,
			"lease_owner " + text + " NOT NULL DEFAULT ''",
			"lease_expires_at " + text,
			"fencing_token BIGINT NOT NULL DEFAULT 1",
			"created_at " + text + " NOT NULL",
			"updated_at " + text + " NOT NULL",
		},
		"_transaction_boundary_intents": {
			"id " + text + " PRIMARY KEY",
			"workspace_id " + idempotencyScopeText + " NOT NULL",
			"owner " + idempotencyScopeText + " NOT NULL",
			"operation " + idempotencyScopeText + " NOT NULL",
			"resource_id " + text + " NOT NULL",
			"idempotency_key " + idempotencyScopeText + " NOT NULL",
			"status " + text + " NOT NULL",
			"payload_json TEXT NOT NULL",
			"compensation_payload_json TEXT NOT NULL",
			"attempt_count INTEGER NOT NULL DEFAULT 0",
			"next_attempt_at " + text + " NOT NULL DEFAULT ''",
			"lease_owner " + text + " NOT NULL DEFAULT ''",
			"lease_expires_at " + text + " NOT NULL DEFAULT ''",
			"fencing_token BIGINT NOT NULL DEFAULT 0",
			"last_error TEXT NOT NULL DEFAULT ''",
			"created_at " + text + " NOT NULL",
			"updated_at " + text + " NOT NULL",
		},
		"_publication_outbox": {
			"id " + text + " PRIMARY KEY",
			"publication_type " + idempotencyScopeText + " NOT NULL DEFAULT 'integration.connector'",
			"tenant_id " + idempotencyScopeText + " NOT NULL DEFAULT ''",
			"workspace_id " + idempotencyScopeText + " NOT NULL",
			"application_key " + idempotencyScopeText + " NOT NULL DEFAULT ''",
			"source_event_id " + idempotencyScopeText + " NOT NULL DEFAULT ''",
			"event_type " + text + " NOT NULL DEFAULT ''",
			"intent_json TEXT NOT NULL DEFAULT '{}'",
			"connector_key " + idempotencyScopeText + " NOT NULL DEFAULT ''",
			"connection_key " + idempotencyScopeText,
			"operation " + idempotencyScopeText + " NOT NULL DEFAULT ''",
			"status " + text + " NOT NULL",
			"payload_json TEXT NOT NULL DEFAULT '{}'",
			"event_id " + text,
			"request_ref TEXT",
			"dedup_key " + idempotencyScopeText + " NOT NULL DEFAULT ''",
			"request_fingerprint " + text + " NOT NULL DEFAULT ''",
			"response_ref TEXT",
			"error TEXT",
			"attempt_count INTEGER NOT NULL DEFAULT 0",
			"next_attempt_at " + text + " NOT NULL DEFAULT ''",
			"last_attempt_at " + text + " NOT NULL DEFAULT ''",
			"lease_owner " + text + " NOT NULL DEFAULT ''",
			"lease_expires_at " + text + " NOT NULL DEFAULT ''",
			"fencing_token BIGINT NOT NULL DEFAULT 0",
			"remote_event_id " + text + " NOT NULL DEFAULT ''",
			"last_error_code " + text + " NOT NULL DEFAULT ''",
			"last_error TEXT NOT NULL DEFAULT ''",
			"terminal_at " + text + " NOT NULL DEFAULT ''",
			"created_by " + text + " NOT NULL DEFAULT ''",
			"created_at " + text + " NOT NULL",
			"updated_at " + text + " NOT NULL",
		},
	}
	return ensureEvidenceTables(ctx, s, tables, text)
}
