// Code generated by npm run brand:sync; DO NOT EDIT.

package productbrand

const (
	DefaultName             = "Domainry"
	DefaultLocalizedName    = "域铸"
	DefaultTagline          = "From business truth to governed software."
	DefaultLocalizedTagline = "从业务事实，到可治理的软件系统。"
	DefaultDescription      = "Governed business application platform"
)
