package operations

import "net/http"

func (h *OperationsHandler) RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("POST /operations/database-retirements", h.discoverDatabaseRetirement)
	mux.HandleFunc("GET /operations/database-retirements", h.listDatabaseRetirements)
	mux.HandleFunc("GET /operations/database-retirements/{retirementID}", h.getDatabaseRetirement)
	mux.HandleFunc("POST /operations/database-retirements/{retirementID}/preview", h.previewDatabaseRetirement)
	mux.HandleFunc("POST /operations/database-retirements/{retirementID}/advance", h.advanceDatabaseRetirement)
	mux.HandleFunc("POST /operations/database-retirements/{retirementID}/execute", h.executeDatabaseRetirement)
	mux.HandleFunc("POST /operations", h.authenticated(h.submitOperation))
	mux.HandleFunc("GET /operations", h.authenticated(h.listOperations))
	mux.HandleFunc("GET /operations/catalog", h.authenticated(h.operationCatalog))
	mux.HandleFunc("GET /operations/controls", h.authenticated(h.listControls))
	mux.HandleFunc("PUT /operations/controls/{controlKind}/{owner}", h.authenticated(h.setControl))
	mux.HandleFunc("POST /operations/leases/{owner}/{resourceID}/force-release", h.authenticated(h.forceReleaseLease))
	mux.HandleFunc("GET /operations/dead-letters/{owner}/{deadLetterID}", h.authenticated(h.inspectDeadLetter))
	mux.HandleFunc("POST /operations/dead-letters/{owner}/{deadLetterID}/{action}", h.authenticated(h.actOnDeadLetter))
	mux.HandleFunc("POST /operations/bulk/dead-letters/dry-run", h.authenticated(h.dryRunBulkDeadLetters))
	mux.HandleFunc("POST /operations/bulk/dead-letters/apply", h.authenticated(h.applyBulkDeadLetters))
	mux.HandleFunc("POST /operations/diagnostics/snapshots", h.authenticated(h.captureDiagnostics))
	mux.HandleFunc("GET /operations/runbooks/{category}", h.authenticated(h.operationRunbook))
	mux.HandleFunc("POST /operations/break-glass", h.authenticated(h.enableBreakGlass))
	mux.HandleFunc("GET /operations/break-glass", h.authenticated(h.listBreakGlass))
	mux.HandleFunc("POST /operations/break-glass/{grantID}/disable", h.authenticated(h.disableBreakGlass))
	mux.HandleFunc("GET /operations/{operationID}", h.authenticated(h.getOperation))
	mux.HandleFunc("GET /operations/idempotency/receipts", h.authenticated(h.receipts))
	mux.HandleFunc("POST /operations/idempotency/receipts/{owner}/{receiptID}/retry", h.authenticated(h.retry))
	mux.HandleFunc("POST /operations/idempotency/receipts/{owner}/{receiptID}/reset", h.authenticated(h.reset))
	mux.HandleFunc("GET /operations/lifecycle/policies", h.authenticated(h.lifecyclePolicies))
	mux.HandleFunc("POST /operations/lifecycle/policies", h.authenticated(h.lifecyclePublishPolicy))
	mux.HandleFunc("POST /operations/lifecycle/legal-holds", h.authenticated(h.lifecycleCreateLegalHold))
	mux.HandleFunc("POST /operations/lifecycle/legal-holds/{holdID}/end", h.authenticated(h.lifecycleEndLegalHold))
	mux.HandleFunc("GET /operations/lifecycle/cleanup/preview", h.authenticated(h.lifecycleCleanupPreview))
	mux.HandleFunc("POST /operations/lifecycle/cleanup/jobs", h.authenticated(h.lifecycleCreateCleanupJob))
	mux.HandleFunc("POST /operations/lifecycle/cleanup/jobs/{jobID}/run", h.authenticated(h.lifecycleRunCleanupJob))
	mux.HandleFunc("GET /operations/lifecycle/metrics", h.authenticated(h.lifecycleMetrics))
	mux.HandleFunc("GET /operations/lifecycle/archive", h.authenticated(h.lifecycleArchiveEntries))
	mux.HandleFunc("POST /operations/lifecycle/subjects", h.authenticated(h.lifecycleCreateSubjectRequest))
	mux.HandleFunc("POST /operations/lifecycle/subjects/{requestID}/verify", h.authenticated(h.lifecycleVerifySubjectRequest))
	mux.HandleFunc("POST /operations/lifecycle/subjects/{requestID}/preview", h.authenticated(h.lifecyclePreviewSubjectRequest))
	mux.HandleFunc("POST /operations/lifecycle/subjects/{requestID}/approve", h.authenticated(h.lifecycleApproveSubjectRequest))
	mux.HandleFunc("POST /operations/lifecycle/subjects/{requestID}/execute", h.authenticated(h.lifecycleExecuteSubjectRequest))
	mux.HandleFunc("GET /operations/lifecycle/subjects/{requestID}/download", h.authenticated(h.lifecycleDownloadSubjectExport))
	mux.HandleFunc("GET /operations/lifecycle/external-erasures", h.authenticated(h.lifecycleExternalErasures))
	mux.HandleFunc("POST /operations/lifecycle/external-erasures/{erasureID}/reconcile", h.authenticated(h.lifecycleReconcileExternalErasure))
	mux.HandleFunc("POST /operations/lifecycle/deletions/replay", h.authenticated(h.lifecycleReplayDeletions))
}
