package runtimeext

import (
	"crypto/sha256"
	"encoding/hex"
	"reflect"
	"strings"
)

const (
	ContractVersion = "runtimeext-v47"
	ContractSHA256  = "b0c653a7a56cfd878b77064e544ac3dcce6f2f1ed252006aedafd648e39ae134"
)

const contractDefinitionV47 = `runtimeext-v47
PackagePath=github.com/domainry/domainry-runtime/pkg/runtimeext
Handler[Capabilities,Input,Output](context.Context,Capabilities,Input)(Output,error)
CapabilityFactory[Capabilities](ActionExecution)(Capabilities,error)
NewTypedBusinessHandler(HandlerDescriptor,CapabilityFactory,Handler)(BusinessHandler,error)
BusinessHandler.Descriptor()HandlerDescriptor
BusinessHandler.Invoke(context.Context,ActionExecution,json.RawMessage)(json.RawMessage,error)
NativeBusinessHandler.InvokeNative(context.Context,ActionExecution,any)(json.RawMessage,bool,error)
ActionExecution.Identity()ExecutionIdentity
ActionExecution.Principal()Principal
ActionExecution.Workspace()Workspace
ActionExecution.Phase()ExecutionPhase
ApplicationTimeZoneExecution.ApplicationTimeZone()(string,error)
ResolveApplicationTimeZone(ActionExecution)(string,error){Source:InvocationApplicationSchemaRevision,Empty:Unavailable,Invalid:Rejected,ServerOrBrowserFallback:Forbidden}
ActionExecution.QueryRecords(context.Context,RecordQuery)(RecordQueryResult,error)
ActionExecution.ApplyRecordMutation(context.Context,RecordMutation)(RecordMutationResult,error)
ActionExecution.StageDurableIntent(context.Context,DurableIntent)(DurableIntentReceipt,error)
ActionExecution.AcquireSynchronousConnectorCall(ActionConnectorCapability)(SynchronousConnectorCallLease,error)
ConditionalUpdateManyExecution.ConditionalUpdateMany(context.Context,ConditionalUpdateManyRequest)(ConditionalUpdateManyResult,error)
ApplyConditionalUpdateMany(context.Context,ActionExecution,ConditionalUpdateManyRequest)(ConditionalUpdateManyResult,error)
ConditionalUpdateManySemantics=one_scoped_select_for_update|explicit_exact_distinct_coverage_field_and_values|every_expected_value_exactly_one_locked_row|no_in_filter_inference|one_conditional_update|expected_affected_exact|same_action_transaction|no_owner_input|max_200
ResolveRecordNotificationRecipient(context.Context,ActionExecution,RecordNotificationRecipientRequest)(string,error)
RecordNotificationRecipientOperation=notification_recipient
VerifyFileClean(context.Context,ActionExecution,FileVerificationRequest)(FileVerificationEvidence,error)
FileOperationVerifyClean=verify_clean
OpenVerifiedFile(context.Context,ActionExecution,VerifiedFileRequest)(VerifiedFile,error)
FileOperationOpenVerified=open_verified
IssueFileDownload(context.Context,ActionExecution,FileDownloadRequest)(FileDownloadTicket,error)
FileOperationIssueDownload=issue_download
CreateDerivedFile(context.Context,ActionExecution,DerivedFileRequest)(DerivedFileEvidence,error)
FileOperationCreateDerived=create_derived
RunBusinessJob(context.Context,ActionExecution,BusinessJobRequest)(BusinessJobReceipt,error)
FileOperationRunJob=run_business_job
OpenVerifiedFileSemantics=exact_workspace|caller_readable_record_field_binding|clean_receipt_and_sha256|exact_stored_bytes
IssueFileDownloadSemantics=exact_workspace|exact_user_and_authorization_revision|caller_readable_record_field_binding|clean_receipt_and_sha256|opaque_file_identity|hmac_signed_two_minute_expiry|download_audit
CreateDerivedFileSemantics=bounded_128_mib|stable_idempotency_key|immutable_content_identity|protected_download_reference|runtime_clean_receipt
RunBusinessJobSemantics=exact_json_payload|exact_target_object|same_action_uow_record_timer|durable_lease_and_fencing|bounded_retry_and_dead_letter|target_action_stable_idempotency_receipt
FileActionGrantDeniedErrorCode=backend.upload.action_grant_denied
WorkflowStartExecution.StageWorkflowStart(context.Context,WorkflowStart)(WorkflowStartReceipt,error)
StageWorkflowStart(context.Context,ActionExecution,WorkflowStart)(WorkflowStartReceipt,error)
WorkflowGrantOperation=start|withdraw
WorkflowWithdrawalExecution.StageWorkflowWithdrawal(context.Context,WorkflowWithdrawal)(WorkflowWithdrawalReceipt,error)
StageWorkflowWithdrawal(context.Context,ActionExecution,WorkflowWithdrawal)(WorkflowWithdrawalReceipt,error)
WorkflowWithdrawalSemantics=exact_descriptor_withdraw_grant|exact_workspace_workflow_object_record_and_initiator|waiting_decision_boundary|process_revision_compare_and_swap|cancel_all_active_children|same_action_uow|business_receipt_and_occupancy_release_by_handler|rollback_together|action_execution_replay
WorkflowGrantDeniedErrorCode=backend.action.workflow_grant_denied
WorkflowStartSemantics=registered_workflow_with_instance_approval_route|descriptor_workflow_start_grant|synchronous_route_validation|same_action_uow|starting_process_and_route_steps_and_intent|activation_by_committed_intent
StageNotification(context.Context,ActionExecution,NotificationIntent)(NotificationReceipt,error)
StageNotificationBatch(context.Context,ActionExecution,[]NotificationIntent)([]NotificationReceipt,error)
NotificationDispatchOperationKey=notification.intent.dispatch
NotificationBatchSizeInvalidErrorCode=backend.notification.action_batch_size_invalid
NotificationBatchMaximum=200
SynchronousConnectorCallLease.Release()
SynchronousConnectorCallSemantics=read_before_write|reserve_or_write_only_from_non_reclaimable_record_timer_action|unresolved_dispatch_never_reclaimed
ConnectorCallAfterWriteErrorCode=backend.connector.call_after_write_forbidden
ActionWriteDuringConnectorCallErrorCode=backend.action.write_during_connector_call_forbidden
ConnectorActionExecutionRequiredErrorCode=backend.connector.action_execution_required
ConnectorActionGrantDeniedErrorCode=backend.connector.action_grant_denied
ConnectorActionSideEffectOutboxErrorCode=backend.connector.action_side_effect_requires_outbox
ProjectExtensionRegistry.RegisterBusinessHandler(BusinessHandler)error
ProjectExtensionRegistry.RegisterAssigneeResolver(AssigneeResolver)error
ProjectExtensionRegistry.RegisterProjectExtensions(ProjectExtensions)error
ProjectExtensionRegistry.Freeze()
ProjectExtensionRegistry.BusinessHandlerBinding(string)(BusinessHandlerBinding,bool)
ProjectExtensionRegistry.BusinessHandlerDescriptors()[]HandlerDescriptor
ProjectExtensionRegistry.AssigneeResolverBinding(string)(AssigneeResolverBinding,bool)
ProjectExtensionRegistry.AssigneeResolverDescriptors()[]AssigneeResolverDescriptor
ProjectExtensionRegistry.Descriptors()[]ProjectExtensionDescriptor
ProjectExtensionRegistry.WorkspaceBootstrapParticipant()WorkspaceBootstrapParticipant
QueryOperation=get,get_for_update,list,exists,count
RecordQueryPagination=after_id
RecordQueryFilterContains=literal_substring|text_long_text_email_phone_url_and_record_id|string_value|preserve_spaces|escape_percent_underscore_tilde|database_collation|null_does_not_match
RecordQuery.StoreOrganization=execution_scoped_catalog_reference|list_only
ExecuteCrossWorkspaceAggregate(context.Context,ActionExecution,CrossWorkspaceAggregateRequest)(CrossWorkspaceAggregateResult,error)
CrossWorkspaceDimensionWorkspace=$workspace
AggregateOperation=count,sum,min,max,avg
ResolveTargetOrganization(ActionExecution)(TargetOrganization,error)
ProvisionStoreOrganization(context.Context,ActionExecution,StoreOrganizationProvisionRequest)(StoreOrganizationProvisionResult,error)
StoreOrganizationProvisionResult=runtime_authoritative_target_id|organization_version|replayed
RenameStoreOrganization(context.Context,ActionExecution,StoreOrganizationRenameRequest)(StoreOrganizationMutationResult,error)
DisableStoreOrganization(context.Context,ActionExecution,StoreOrganizationDisableRequest)(StoreOrganizationMutationResult,error)
TargetOrganizationSource=explicit,explicit_or_sole_authorized_store,record_owner,provisioned_store,delivered_organization_unit
ExplicitOrSoleAuthorizedStore=explicit_identity_resolve_and_action_scope|omitted_exactly_one_complete_active_authorized_catalog|zero_multiple_disabled_or_continuation_denied
CreateOrganizationUnit(context.Context,ActionExecution,OrganizationUnitDeliveryRequest)(OrganizationUnitDeliveryResult,error)
ResolveOrganizationUnit(context.Context,ActionExecution,OrganizationUnitResolveRequest)(OrganizationUnitDeliveryResult,error)
OrganizationUnitDeliveryOperation=create,resolve
OrganizationUnitDeliveryNodeType=region,department,team,warehouse|company_and_store_forbidden
OrganizationUnitDeliveryParentSource=workspace_company,target_organization
OrganizationUnitDeliveryAuthority=project_model_and_handler_descriptor_exact_match|runtime_workspace_and_bearer|runtime_parent_resolution|same_action_uow|opaque_result|no_workspace_bearer_parent_or_owner_input
DeliverIdentity(context.Context,ActionExecution,IdentityHandlerDeliveryRequest)(IdentityHandlerDeliveryResult,error)
StageAccountErasure(context.Context,ActionExecution,AccountErasureStageRequest)(AccountErasureReceipt,error)
GetAccountErasure(context.Context,ActionExecution,AccountErasureGetRequest)(AccountErasureReceipt,error)
AccountErasureSemantics=static_profile_and_request_mapping|locked_subject_intent|independent_approver|exact_organization|identity_and_binding_cas|joined_queue_and_disable|effects_after_commit|source_owned_retry|success_only_after_all_owners
ResolveBoundIdentity(context.Context,ActionExecution,string)(IdentityBoundIdentity,error)
ResolveBoundIdentities(context.Context,ActionExecution,[]string)([]IdentityBoundIdentity,error)
ResolveBoundIdentityProfile(context.Context,ActionExecution,string,IdentityHandlerProfileBindingSelector)(IdentityBoundIdentity,error)
IdentityHandlerResolveBatch=distinct_nonempty_user_ids|max_200|one_action_uow|stable_input_order
IdentityHandlerProfileResolution=generated_static_binding_key_and_object|caller_profile_id|identity_owned_cas_version|active_exact_user
IdentityHandlerOperation=create,update,disable,resolve
IdentityHandlerLoginMode=none,password
ExecuteStoreOrganizationCatalog(context.Context,ActionExecution,StoreOrganizationCatalogRequest)(StoreOrganizationCatalogPage,error)
ExecuteStoreOrganizationCatalogResolve(context.Context,ActionExecution,string)(StoreOrganizationCatalogItem,error)
IssueStoreOrganizationCatalogItem(StoreOrganizationCatalogItem)(StoreOrganizationCatalogItem,string,error)
StoreOrganizationCatalogResolve=exact_authorized_identity_organization_id|issued_current_action_reference|same_action_uow
StoreOrganizationCatalogOwnedRecordLookup=generated_ListForStore|issued_current_action_reference|record_read_effect|workspace_and_identity_scope|read_only
ExecuteWorkspaceIdentityUsage(context.Context,ActionExecution,WorkspaceIdentityUsageRequest)(WorkspaceIdentityUsagePage,error)
ExecuteWorkspaceIdentityUsageResolve(context.Context,ActionExecution,WorkspaceIdentityUsageResolveRequest)(WorkspaceIdentityUsageResolveResult,error)
WorkspaceIdentityUsageMaximumPageSize=100
WorkspaceIdentityUsageProjection=canonical_code,display_name,commercial_plan,included_user_limit,max_user_limit,identity_account_counts|physical_workspace_id_withheld
WorkspaceIdentityUsageResolve=canonical_workspace_code,expected_top_level_workspace_revision|active_workspace_locked_and_rechecked|typed_commercial_configuration|identity_account_counts|same_action_uow|physical_workspace_id_withheld
ProjectExtensions.BusinessHandlers=[]BusinessHandler
ProjectExtensions.AssigneeResolvers=[]AssigneeResolver
ProjectExtensions.WorkspaceBootstrapParticipant=WorkspaceBootstrapParticipant
ProjectExtensions.Definitions=ProjectDefinitions
ProjectDefinitions=code_owned_behavior_only|reports|public_resources|workflows|business_calendars|schedules|automation|notification|integration_mappings|agents
ProjectDefinitionRegistry=stable_key|typed_descriptor|computed_sha256|freeze|duplicate_rejection|detached_snapshot
ReportDefinition=ReportSchema|OperationStateExamples|SensitiveFieldPolicies|ExportControls|single_immutable_report_definition|object_sql_owned_in_go
ProjectExtensionDescriptor=closed_kind_envelope|business_handler|workflow_assignee_resolver|workspace_bootstrap
AssigneeResolver.Descriptor()AssigneeResolverDescriptor
AssigneeResolver.Resolve(context.Context,AssigneeResolverCapabilities,AssigneeResolverContext)([]AssigneeResolverCandidate,error)
AssigneeResolverCapabilities=GetRecord|ListRecords|FollowRelation|FindUser|UsersForRole
AssigneeResolverReadSemantics=workspace_scoped|principal_authorized|descriptor_projected|query_and_row_bounded|context_budgeted
AssigneeResolverResultSemantics=active_users|max_candidates|declared_candidate_roles|stable_ordered_evidence|duplicate_evidence_merge
WorkspaceBootstrapParticipant.Descriptor()WorkspaceBootstrapDescriptor
WorkspaceBootstrapParticipant.BuildWorkspaceBootstrap(context.Context,WorkspaceBootstrapContext,map[string]any)([]WorkspaceBootstrapRecord,error)
WorkspaceBootstrapInputExactDecimal=canonical_decimal_string|no_binary_float|exact_range_validation
WorkspaceBootstrapRuntimeOwnedFields=workspace_id,id,owner_org_id,created_at,updated_at
RuntimeWorkspaceRoleCatalog=project_model_defined_roles|bootstrap=provision_to_workspaces_and_audience_any,user,business_profile_and_assignment_manual,request_only|complete_publication=all_project_model_roles|initial_workspace_administrator_role=explicit_provisioned_audience_any,user_assignment_manual_without_required_binding
WorkspaceProvisioningVocabulary=workspace_name,workspace_code
AcceptanceFixtureContract=runtime-acceptance-fixture-v2|workspace_code
`

// ComputedContractSHA256 returns the canonical public contract identity used
// by source-owned project composition and Runtime readiness checks.
func ComputedContractSHA256() string {
	structs := []any{
		BusinessProfileReference{}, Principal{}, Workspace{}, ExecutionIdentity{}, ActionObjectCapability{}, ActionConnectorCapability{}, FileVerificationRequest{}, FileVerificationEvidence{}, FileRecordBinding{}, VerifiedFileRequest{}, VerifiedFile{}, FileDownloadRequest{}, FileDownloadTicket{}, DerivedFileRequest{}, DerivedFileEvidence{}, BusinessJobRequest{}, BusinessJobReceipt{}, RecordNotificationRecipientRequest{},
		CrossWorkspaceAggregateDimension{}, CrossWorkspaceAggregateDimensionTransform{}, CrossWorkspaceAggregateDateBucketTransform{}, CrossWorkspaceAggregateMeasure{}, CrossWorkspaceAggregateFilterCapability{}, CrossWorkspaceAggregateCapability{}, CrossWorkspaceAggregateFilter{}, CrossWorkspaceAggregateRequest{}, CrossWorkspaceAggregateRow{}, CrossWorkspaceAggregateResult{},
		ActionTargetOrganizationCapability{}, TargetOrganization{}, OrganizationUnitDeliveryCapability{}, OrganizationUnitDeliveryRequest{}, OrganizationUnitResolveRequest{}, OrganizationUnit{}, OrganizationUnitDeliveryResult{}, StoreOrganizationProvisionRequest{}, StoreOrganizationProvisionResult{}, StoreOrganizationRenameRequest{}, StoreOrganizationDisableRequest{}, StoreOrganizationMutationResult{}, ActionStoreOrganizationMutationCapability{},
		AccountErasureCapability{}, AccountErasureStageRequest{}, AccountErasureGetRequest{}, AccountErasureReceipt{},
		IdentityProfileBindingCapability{}, IdentityHandlerDeliveryCapability{}, IdentityUser{}, IdentityHandlerUserMutation{}, IdentityHandlerProfileBindingMutation{}, IdentityHandlerDeliveryRequest{}, IdentityHandlerProfileBinding{}, IdentityHandlerProfileBindingSelector{}, IdentityHandlerDeliveryResult{}, IdentityBoundIdentity{},
		StoreOrganizationCatalogCapability{}, StoreOrganizationCatalogRequest{}, StoreOrganizationCatalogItem{}, StoreOrganizationCatalogPage{},
		WorkspaceIdentityUsageCapability{}, WorkspaceIdentityUsageRequest{}, WorkspaceIdentityUsageResolveRequest{}, WorkspaceIdentityAccountCounts{}, WorkspaceCommercialTerms{}, WorkspaceCommercialConfiguration{}, WorkspaceIdentityUsageItem{}, WorkspaceIdentityUsagePage{}, WorkspaceIdentityUsageResolveResult{},
		WorkspaceBootstrapInputField{}, WorkspaceBootstrapRecordCapability{}, WorkspaceBootstrapDescriptor{}, WorkspaceBootstrapContext{}, WorkspaceBootstrapRecord{},
		HandlerDescriptor{}, BusinessHandlerBinding{}, ProjectExtensionDescriptor{},
		AssigneeResolverConfigField{}, AssigneeResolverRecordCapability{}, AssigneeResolverRelationCapability{}, AssigneeResolverDescriptor{}, AssigneeRecordFilter{}, AssigneeRecordListRequest{}, AssigneeRelationRequest{}, AssigneeRecord{}, AssigneeIdentityUser{}, AssigneeResolverContext{}, AssigneeEvidenceFact{}, AssigneeResolverCandidate{}, AssigneeResolverBinding{},
		Record{}, Filter{}, Sort{}, RecordQuery{}, RecordQueryResult{},
		Predicate{}, Arithmetic{}, RecordMutation{}, RecordMutationResult{}, ConditionalUpdateManyExactCoverage{}, ConditionalUpdateManyRequest{}, ConditionalUpdateManyResult{},
		DurableIntent{}, DurableIntentReceipt{}, BusinessError{}, ProjectExtensions{}, ProjectDefinitions{}, ReportDefinition{}, PublicResourceDefinition{}, ProjectDefinitionIdentity{},
		NotificationVariable{}, NotificationIntent{}, NotificationReceipt{},
		WorkflowGrant{}, WorkflowRouteStep{}, WorkflowStart{}, WorkflowStartReceipt{}, WorkflowWithdrawal{}, WorkflowWithdrawalReceipt{},
	}
	var definition strings.Builder
	definition.WriteString(contractDefinitionV47)
	for _, value := range structs {
		current := reflect.TypeOf(value)
		definition.WriteString(current.Name())
		definition.WriteByte('{')
		for index := 0; index < current.NumField(); index++ {
			if index > 0 {
				definition.WriteByte(',')
			}
			field := current.Field(index)
			definition.WriteString(field.Name)
			definition.WriteByte(':')
			definition.WriteString(field.Type.String())
		}
		definition.WriteString("}\n")
	}
	sum := sha256.Sum256([]byte(definition.String()))
	return hex.EncodeToString(sum[:])
}
