package openapi

import (
	metadatamodel "github.com/domainry/domainry-runtime/runtime/domain/metadata/model"
	surfacemodel "github.com/domainry/domainry-runtime/runtime/domain/surface/model"
)

func addIntegrationOpenAPIPaths(paths map[string]any, _ metadatamodel.MetadataSchemaSnapshot) {
	paths["/tenant-admin/integrations/connectors"] = map[string]any{"get": openAPIOperation("listIntegrationConnectors", "Integration Administration", "Runtime-owned Connector catalog and connection state", openAPIAdminSecurity(), openAPIJSONResponse("Connectors", openAPIObject(nil)))}
	paths["/tenant-admin/integrations/connections"] = map[string]any{"get": openAPIOperation("listIntegrationConnections", "Integration Administration", "Integration connections", openAPIAdminSecurity(), openAPIJSONResponse("Connections", openAPIArray(openAPIRef("IntegrationConnection"))))}
	paths["/tenant-admin/integrations/connections/{connectionKey}"] = map[string]any{
		"get":    openAPIOperation("getIntegrationConnection", "Integration Administration", "Get one integration connection", openAPIAdminSecurity(), openAPIPathParameter("connectionKey", "Connection key"), openAPIJSONResponse("Connection", openAPIRef("IntegrationConnection"))),
		"put":    openAPIOperation("upsertIntegrationConnection", "Integration Administration", "Create or update integration connection", openAPIAdminSecurity(), openAPIPathParameter("connectionKey", "Connection key"), openAPIJSONRequest(openAPIRef("IntegrationConnectionUpsertRequest")), openAPIJSONResponse("Connection", openAPIRef("IntegrationConnection"))),
		"delete": openAPIOperation("deleteIntegrationConnection", "Integration Administration", "Delete an unreferenced integration connection", openAPIAdminSecurity(), openAPIPathParameter("connectionKey", "Connection key"), openAPIJSONResponse("Connection deleted", openAPIObject(nil))),
	}
	paths["/tenant-admin/integrations/connections/{connectionKey}/validate"] = map[string]any{"post": openAPIOperation("validateIntegrationConnection", "Integration Administration", "Validate one integration connection payload without persisting", openAPIAdminSecurity(), openAPIPathParameter("connectionKey", "Connection key"), openAPIJSONRequest(openAPIRef("IntegrationConnectionUpsertRequest")), openAPIJSONResponse("Connection validation", openAPIObject(nil)))}
	paths["/tenant-admin/integrations/connections/{connectionKey}/versions"] = map[string]any{"get": openAPIOperation("listIntegrationConnectionVersions", "Integration Administration", "List persisted audit revisions for one integration connection", openAPIAdminSecurity(), openAPIPathParameter("connectionKey", "Connection key"), openAPIJSONResponse("Connection revisions", openAPIObject(nil)))}
	paths["/tenant-admin/integrations/api-keys"] = map[string]any{
		"get":  openAPIOperation("listIntegrationAPIKeys", "Integration Administration", "Workspace API keys without raw token values", openAPIAdminSecurity(), openAPIJSONResponse("API keys", openAPIArray(openAPIObject(nil)))),
		"post": openAPIOperation("createIntegrationAPIKey", "Integration Administration", "Create generated-app API key", openAPIAdminSecurity(), openAPIJSONRequest(openAPIObject(nil)), openAPIJSONResponse("API key", openAPIObject(nil))),
	}
	paths["/tenant-admin/integrations/connections/{connectionKey}/test-operation"] = map[string]any{"post": openAPIOperation("testConnectorOperation", "Integration Administration", "Confirm and execute one catalog Connector operation with invocation evidence", openAPIAdminSecurity(), openAPIPathParameter("connectionKey", "Connection key"), openAPIJSONRequest(openAPIObject(nil)), openAPIJSONResponse("Operation test result", openAPIObject(nil)))}
	paths["/tenant-admin/integrations/connections/{connectionKey}/oauth/google/start"] = map[string]any{"post": openAPIOperation("startGoogleOAuth", "Integration Administration", "Create a signed, expiring Google OAuth authorization URL for one connection", openAPIAdminSecurity(), openAPIPathParameter("connectionKey", "Connection key"), openAPIJSONRequest(openAPIObject(nil)), openAPIJSONResponse("Google OAuth authorization", openAPIObject(nil)))}

	paths["/integrations/webhooks/{workspaceID}/{connectionKey}"] = map[string]any{"post": openAPIOperation("receiveWorkspaceIntegrationWebhook", "Integration Webhooks", "Receive and verify a provider webhook in one Runtime workspace", openAPIPublicSecurity(), openAPIPathParameter("workspaceID", "Runtime workspace ID"), openAPIPathParameter("connectionKey", "Opaque integration Connection key"), openAPIJSONRequest(openAPIObject(nil)), openAPIJSONResponse("Verified webhook receipt", openAPIObject(nil)))}
	paths["/v1/notification-deliveries:accept"] = map[string]any{"post": openAPIOperation("acceptNotificationDelivery", "Notification Delivery Gateway", "Identity-authenticated durable acceptance of one Notification SaaS channel plan", openAPIProtocolAudience("notification_service_service"), openAPIServiceCredentialSecurity(), openAPIJSONRequest(openAPIObject(nil)), openAPIJSONResponse("Stable Integration outbox receipt", openAPIObject(nil)))}
	paths["/v1/scheduler-triggers:accept"] = map[string]any{"post": openAPIOperation("acceptSchedulerTrigger", "Scheduler Dispatch Gateway", "Identity-authenticated execution callback for one Scheduler-owned run", openAPIProtocolAudience("scheduler_service_service"), openAPIServiceCredentialSecurity(), openAPIJSONRequest(openAPIObject(nil)), openAPIJSONResponse("Stable downstream receipt", openAPIObject(nil)))}
	paths["/integrations/google/oauth/callback"] = map[string]any{"get": openAPIOperation("completeGoogleOAuth", "Integration OAuth", "Verify one signed Google OAuth callback, persist encrypted tokens and activate Gmail polling", openAPIProtocolAudience("google_oauth_provider"), openAPIPublicSecurity(), openAPIResponse("OAuth completion page", "text/html", map[string]any{"type": "string"}))}
	remoteNotificationSurfaces := openAPIProductSurfaces(surfacemodel.ProductSurfaceBusinessWorkspace)
	paths["/business/notifications/web-push/readiness"] = map[string]any{"get": openAPIOperation("getWebPushReadiness", "Remote notifications", "Read Web Push readiness and the public VAPID application-server key without secret material", remoteNotificationSurfaces, openAPIAdminSecurity(), openAPIJSONResponse("Readiness", openAPIRef("WebPushReadiness")))}
	paths["/business/notifications/web-push/subscriptions"] = map[string]any{"get": openAPIOperation("listWebPushSubscriptions", "Remote notifications", "List the current authenticated user's Runtime-owned Web Push subscriptions without endpoint or key material", remoteNotificationSurfaces, openAPIAdminSecurity(), openAPIJSONResponse("Subscriptions", openAPIRef("WebPushSubscriptionList")))}
	paths["/business/notifications/web-push/subscriptions/{subscriptionID}"] = map[string]any{"put": openAPIOperation("upsertWebPushSubscription", "Remote notifications", "Create or replace the current user's explicit Web Push opt-in subscription", remoteNotificationSurfaces, openAPIAdminSecurity(), openAPIPathParameter("subscriptionID", "Stable client subscription identity"), openAPIJSONRequest(openAPIRef("WebPushSubscriptionUpsertRequest")), openAPIJSONResponse("Subscription", openAPIRef("WebPushSubscription")))}
	paths["/business/notifications/web-push/subscriptions/{subscriptionID}/revoke"] = map[string]any{"post": openAPIOperation("revokeWebPushSubscription", "Remote notifications", "Revoke the current user's Web Push subscription and erase endpoint key material", remoteNotificationSurfaces, openAPIAdminSecurity(), openAPIPathParameter("subscriptionID", "Subscription identity"), openAPIJSONResponse("Subscription", openAPIRef("WebPushSubscription")))}
	paths["/integrations/web-push/subscriptions/cleanup-expired"] = map[string]any{"post": openAPIOperation("cleanupExpiredWebPushSubscriptions", "Remote notifications", "Erase expired endpoint key material in the current workspace", openAPIProductSurfaces(surfacemodel.ProductSurfaceAdminConsole), openAPIAdminSecurity(), openAPIJSONResponse("Cleanup result", openAPIObject(nil)))}
	paths["/integrations/entrypoints/workflows/{workflowKey}/run"] = map[string]any{"post": openAPIOperation("runIntegrationWorkflow", "Integration Entrypoints", "Run workflow through generated-app integration permissions", openAPIIntegrationSecurity(), openAPIPathParameter("workflowKey", "Workflow key"), openAPIJSONRequest(openAPIObject(nil)), openAPIJSONResponse("Workflow result", openAPIObject(nil)))}
	paths["/integrations/entrypoints/objects/{objectKey}/records/{recordID}/actions/{actionKey}"] = map[string]any{"post": openAPIOperation("executeIntegrationAction", "Integration Entrypoints", "Execute object action through generated-app integration permissions", openAPIIntegrationSecurity(), openAPIPathParameter("objectKey", "Object key"), openAPIPathParameter("recordID", "Record ID"), openAPIPathParameter("actionKey", "Action key"), openAPIJSONRequest(openAPIRef("IntegrationEntrypointActionRequest")), openAPIJSONResponse("Action result", openAPIObject(nil)))}
	paths["/integrations/agents/{agentKey}/tools/{toolKey}/invoke"] = map[string]any{"post": openAPIOperation("invokeIntegrationAgentTool", "Integration Entrypoints", "Invoke agent tool through generated-app integration permissions", openAPIIntegrationSecurity(), openAPIPathParameter("agentKey", "Agent key"), openAPIPathParameter("toolKey", "Tool key"), openAPIJSONRequest(openAPIObject(nil)), openAPIJSONResponse("Tool result", openAPIObject(nil)))}
}
