package agentdialog

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"html"
	"strings"
)

func agentAnalysisProposalSuggestion(spec map[string]any, intent string, queryRef string) map[string]any {
	if spec == nil {
		return nil
	}
	followUp, ok := spec["follow_up"].(map[string]any)
	if !ok || len(followUp) == 0 {
		return nil
	}
	title := agentAnalysisStringFromMap(followUp, "title")
	if title == "" {
		title = "Create follow-up task"
	}
	kind := agentAnalysisStringFromMap(followUp, "kind")
	if kind == "" {
		kind = "analysis_follow_up"
	}
	riskLevel := agentAnalysisStringFromMap(followUp, "risk_level")
	if riskLevel == "" {
		riskLevel = "medium"
	}
	reference := agentAnalysisStringFromMap(followUp, "reference")
	if reference == "" {
		reference = queryRef
	}
	policy := agentAnalysisRecommendationPolicy(spec, followUp, riskLevel)
	proposed := agentAnalysisFollowUpProposed(followUp)
	if len(policy) > 0 {
		proposed["recommendation_policy"] = policy
	}
	return map[string]any{
		"title":                 title,
		"summary":               valueOrDefault(agentAnalysisStringFromMap(followUp, "summary"), intent),
		"kind":                  kind,
		"risk_level":            riskLevel,
		"run_mode":              "suggested_write",
		"reference":             reference,
		"rollback":              agentAnalysisStringFromMap(followUp, "rollback"),
		"approval":              "approval_required",
		"recommendation_policy": policy,
		"proposed":              proposed,
	}
}

func agentAnalysisRecommendationPolicy(spec map[string]any, followUp map[string]any, riskLevel string) map[string]any {
	policy := mapFromAny(followUp["recommendation_policy"])
	anomalyType := agentAnalysisStringFromMap(followUp, "anomaly_type")
	if anomalyType == "" {
		anomalyType = agentAnalysisSpecString(spec, "anomaly_type")
	}
	if anomalyType == "" && len(policy) == 0 {
		return nil
	}
	policyID := agentAnalysisPolicyString(policy["policy_id"])
	if policyID == "" {
		policyID = agentAnalysisDefaultPolicyID(anomalyType)
	}
	recommendedAction := agentAnalysisPolicyString(policy["recommended_action"])
	if recommendedAction == "" {
		recommendedAction = agentAnalysisDefaultRecommendedAction(anomalyType)
	}
	reason := agentAnalysisPolicyString(policy["reason"])
	if reason == "" {
		reason = "Generated by the analysis gateway from the scoped anomaly signal and follow-up request."
	}
	severity := agentAnalysisPolicyString(policy["severity"])
	if severity == "" {
		severity = riskLevel
	}
	return map[string]any{
		"policy_id":          policyID,
		"anomaly_type":       valueOrDefault(anomalyType, "analysis_anomaly"),
		"severity":           valueOrDefault(severity, "medium"),
		"recommended_action": valueOrDefault(recommendedAction, "create_follow_up_proposal"),
		"review_required":    true,
		"reason":             reason,
	}
}

func agentAnalysisPolicyString(value any) string {
	if value == nil {
		return ""
	}
	return strings.TrimSpace(fmt.Sprint(value))
}

func agentAnalysisDefaultPolicyID(_ string) string {
	return "analysis_policy.generic_follow_up"
}

func agentAnalysisDefaultRecommendedAction(_ string) string {
	return "create_follow_up_proposal"
}

func agentAnalysisFollowUpProposed(followUp map[string]any) map[string]any {
	proposed := map[string]any{}
	if binding := mapFromAny(followUp["action_binding"]); len(binding) > 0 {
		proposed["action_binding"] = binding
	}
	if binding := mapFromAny(followUp["workflow_binding"]); len(binding) > 0 {
		proposed["workflow_binding"] = binding
	}
	if diff := agentAnalysisAnyList(followUp["diff"]); len(diff) > 0 {
		proposed["diff"] = diff
	}
	if affected := agentAnalysisAnyList(followUp["affected_records"]); len(affected) > 0 {
		proposed["affected_records"] = affected
	}
	return proposed
}

func agentAnalysisStringFromMap(values map[string]any, key string) string {
	if values == nil {
		return ""
	}
	text, _ := values[key].(string)
	return strings.TrimSpace(text)
}

func agentAnalysisProposalHTML(suggestion map[string]any) string {
	if len(suggestion) == 0 {
		return ""
	}
	title := strings.TrimSpace(fmt.Sprint(suggestion["title"]))
	summary := strings.TrimSpace(fmt.Sprint(suggestion["summary"]))
	kind := strings.TrimSpace(fmt.Sprint(suggestion["kind"]))
	riskLevel := strings.TrimSpace(fmt.Sprint(suggestion["risk_level"]))
	reference := strings.TrimSpace(fmt.Sprint(suggestion["reference"]))
	rollback := strings.TrimSpace(fmt.Sprint(suggestion["rollback"]))
	proposed := mapFromAny(suggestion["proposed"])
	policy := mapFromAny(suggestion["recommendation_policy"])
	if title == "" {
		title = "Create follow-up task"
	}
	if riskLevel == "" {
		riskLevel = "medium"
	}
	proposedAttr := ""
	if len(proposed) > 0 {
		proposedAttr = ` data-proposed-json="` + html.EscapeString(agentAnalysisEncodeProposalPayload(proposed)) + `"`
	}
	return `<article data-card-type="proposal_card" class="agent-card agent-card-proposal" data-source-count="` + html.EscapeString(fmt.Sprint(len(agentAnalysisAnyList(proposed["affected_records"])))) + `">` +
		`<h3>` + html.EscapeString(title) + `</h3>` +
		`<p>` + html.EscapeString(summary) + `</p>` +
		agentAnalysisRecommendationPolicyHTML(policy) +
		agentAnalysisProposalDiffHTML(proposed) +
		agentAnalysisProposalAffectedHTML(proposed) +
		`<p data-risk-level="` + html.EscapeString(riskLevel) + `" data-approval-required="true" data-rollback="` + html.EscapeString(rollback) + `">Approval required before creating follow-up work.</p>` +
		`<button data-action="create_proposal" data-title="` + html.EscapeString(title) + `" data-proposal-kind="` + html.EscapeString(kind) + `" data-run-mode="suggested_write" data-risk-level="` + html.EscapeString(riskLevel) + `" data-reference="` + html.EscapeString(reference) + `"` + proposedAttr + `>Create follow-up proposal</button>` +
		`</article>`
}

func agentAnalysisRecommendationPolicyHTML(policy map[string]any) string {
	if len(policy) == 0 {
		return ""
	}
	return `<div data-evidence-kind="recommendation_policy" data-policy-id="` + html.EscapeString(agentAnalysisPolicyString(policy["policy_id"])) + `" data-anomaly-type="` + html.EscapeString(agentAnalysisPolicyString(policy["anomaly_type"])) + `" data-severity="` + html.EscapeString(agentAnalysisPolicyString(policy["severity"])) + `">` +
		`<span data-recommended-action="` + html.EscapeString(agentAnalysisPolicyString(policy["recommended_action"])) + `">` + html.EscapeString(agentAnalysisPolicyString(policy["reason"])) + `</span>` +
		`</div>`
}

func agentAnalysisAnyList(value any) []any {
	if typed, ok := value.([]any); ok {
		return typed
	}
	return nil
}

func agentAnalysisEncodeProposalPayload(proposed map[string]any) string {
	raw, err := json.Marshal(proposed)
	if err != nil {
		return ""
	}
	return base64.StdEncoding.EncodeToString(raw)
}
