package contract

import capabilitycontract "github.com/domainry/domainry-runtime/runtime/domain/capability/contract"

func ApplicationSchemaFieldAuthoringCapability() capabilitycontract.CapabilityAuthoringDefinition {
	payload := metadataFieldPayloadSchema(ApplicationSchemaAuthoringFieldTypes())
	return capabilitycontract.CapabilityAuthoringDefinition{
		Key: "schema.field", Status: "supported", Lifecycle: "versioned_metadata",
		SystemDraftResourceType: "field",
		Parameters: []capabilitycontract.CapabilityAuthoringParameter{
			{Key: "name", Type: "string", Required: true, MinLength: metadataIntPointer(1)},
			{Key: "type", Type: "string", Required: true, Enum: ApplicationSchemaAuthoringFieldTypes()},
			{Key: "required", Type: "boolean", Default: false}, {Key: "unique", Type: "boolean", Default: false},
			{Key: "default_value", Type: "any"}, {Key: "min_length", Type: "integer", Minimum: metadataFloatPointer(0)},
			{Key: "max_length", Type: "integer", Minimum: metadataFloatPointer(0)}, {Key: "minimum", Type: "number"}, {Key: "maximum", Type: "number"},
			{Key: "precision", Type: "integer", Minimum: metadataFloatPointer(1), Maximum: metadataFloatPointer(38), RequiredWhen: map[string]any{"type": "currency"}, Default: 19},
			{Key: "scale", Type: "integer", Minimum: metadataFloatPointer(0), Maximum: metadataFloatPointer(38), RequiredWhen: map[string]any{"type": "currency"}, Default: 2},
			{Key: "rounding_mode", Type: "string", Enum: []string{"ceiling", "down", "floor", "half_even", "half_up", "up"}, RequiredWhen: map[string]any{"type": "currency"}, Default: "half_even"},
			{Key: "currency_code", Type: "currency_code", Format: "iso-4217", RequiredWhen: map[string]any{"type": "currency"}, Default: "XXX"},
			{Key: "allowed_mime_types", Type: "array", ItemSchema: "mime_type"},
			{Key: "max_size_bytes", Type: "integer", Minimum: metadataFloatPointer(1), Maximum: metadataFloatPointer(5 << 20), Default: 5 << 20},
			{Key: "max_files", Type: "integer", Minimum: metadataFloatPointer(1), Maximum: metadataFloatPointer(100), RequiredWhen: map[string]any{"type": "file_list"}, Default: 10},
			{Key: "scan_required", Type: "boolean", Default: true},
			{Key: "options", Type: "array", ItemSchema: "stable_option"},
			{Key: "max_items", Type: "integer", Minimum: metadataFloatPointer(1), Maximum: metadataFloatPointer(1000), RequiredWhen: map[string]any{"type": "multi_select"}, Default: 100},
			{Key: "json_shape", Type: "string", Enum: []string{"array", "object"}, RequiredWhen: map[string]any{"type": "json"}, Default: "object"},
			{Key: "max_json_bytes", Type: "integer", Minimum: metadataFloatPointer(1), Maximum: metadataFloatPointer(1 << 20), RequiredWhen: map[string]any{"type": "json"}, Default: 64 << 10},
		},
		Permissions: []string{"runtime.appschema.validate_application_definition"}, AuditEvents: []string{"metadata_definition_upserted"},
		ValidationEndpoint: "POST /application-schema/definitions/field/{resourceKey}/validate", ConfigurationRoutes: metadataConfigurationRoutes("field"),
		ResourceOperations:       metadataResourceOperations("field"),
		ResourceKeyPathParameter: "resourceKey",
		InputSchema:              metadataAuthoringRequestSchema(payload, true), OutputSchema: metadataAuthoringOutputSchema(payload),
		OutputVariables: []capabilitycontract.CapabilityAuthoringOutput{
			{Name: "field_key", JSONPointer: "/definition/payload/key", Type: "field_key", VisibleTo: "subsequent_capability_calls"},
			{Name: "schema_hash", JSONPointer: "/definition/schema_hash", Type: "schema_hash", VisibleTo: "subsequent_capability_calls"},
		},
		ReferenceContracts: []capabilitycontract.CapabilityAuthoringReference{metadataObjectReference("/object_key")},
		Execution:          metadataAuthoringExecution("schema.field"),
		Errors: []capabilitycontract.CapabilityAuthoringError{
			{Code: "backend.metadata.field_definition_invalid", FieldPath: "field", MessageKey: "backend.metadata.field_definition_invalid"},
			{Code: "backend.metadata.field_key_mismatch", FieldPath: "payload.key", ParameterKeys: []string{"field"}, MessageKey: "backend.metadata.field_key_mismatch"},
			{Code: "backend.validation.required", FieldPath: "field", ParameterKeys: []string{"field"}, MessageKey: "backend.validation.required"},
			{Code: "backend.decimal.precision_invalid", FieldPath: "config.precision", MessageKey: "backend.decimal.precision_invalid"},
			{Code: "backend.decimal.scale_invalid", FieldPath: "config.scale", MessageKey: "backend.decimal.scale_invalid"},
			{Code: "backend.decimal.rounding_mode_invalid", FieldPath: "config.rounding_mode", MessageKey: "backend.decimal.rounding_mode_invalid"},
			{Code: "backend.decimal.currency_code_invalid", FieldPath: "config.currency_code", MessageKey: "backend.decimal.currency_code_invalid"},
			{Code: "backend.file.allowed_mime_types_invalid", FieldPath: "config.allowed_mime_types", MessageKey: "backend.file.allowed_mime_types_invalid"},
			{Code: "backend.file.max_size_invalid", FieldPath: "config.max_size_bytes", MessageKey: "backend.file.max_size_invalid"},
			{Code: "backend.file.max_files_invalid", FieldPath: "config.max_files", MessageKey: "backend.file.max_files_invalid"},
			{Code: "backend.file.scan_required_invalid", FieldPath: "config.scan_required", MessageKey: "backend.file.scan_required_invalid"},
			{Code: "backend.file.unique_unsupported", FieldPath: "unique", MessageKey: "backend.file.unique_unsupported"},
			{Code: "backend.file.default_unsupported", FieldPath: "default_value", MessageKey: "backend.file.default_unsupported"},
			{Code: "backend.file.config_on_non_file", FieldPath: "config", MessageKey: "backend.file.config_on_non_file"},
			{Code: "backend.structured.unique_unsupported", FieldPath: "unique", MessageKey: "backend.structured.unique_unsupported"},
			{Code: "backend.structured.indexed_invalid", FieldPath: "config.indexed", MessageKey: "backend.structured.indexed_invalid"},
			{Code: "backend.structured.index_unsupported", FieldPath: "config.indexed", MessageKey: "backend.structured.index_unsupported"},
			{Code: "backend.multi_select.max_items_invalid", FieldPath: "config.max_items", MessageKey: "backend.multi_select.max_items_invalid"},
			{Code: "backend.json.shape_invalid", FieldPath: "config.json_shape", MessageKey: "backend.json.shape_invalid"},
			{Code: "backend.json.max_size_invalid", FieldPath: "config.max_json_bytes", MessageKey: "backend.json.max_size_invalid"},
			{Code: "backend.json.options_unsupported", FieldPath: "options", MessageKey: "backend.json.options_unsupported"},
			{Code: "backend.structured.config_on_non_structured", FieldPath: "config", MessageKey: "backend.structured.config_on_non_structured"},
		},
		Examples: []capabilitycontract.CapabilityAuthoringExample{
			{Name: "minimal_valid", Value: map[string]any{"object_key": "order", "expected_schema_hash": "$instance.schema_hash", "payload": map[string]any{"name": "Status", "type": "text", "required": false}}},
			{Name: "representative", Value: map[string]any{"object_key": "order", "expected_schema_hash": "$instance.schema_hash", "payload": map[string]any{"name": "Amount", "type": "currency", "required": true, "config": map[string]any{"precision": 19, "scale": 2, "rounding_mode": "half_even", "currency_code": "CNY"}}}},
			{Name: "invalid_with_repair", Value: map[string]any{"object_key": "order", "expected_schema_hash": "$instance.schema_hash", "payload": map[string]any{"name": "Amount", "type": "currency", "config": map[string]any{"precision": 2, "scale": 3}}}, ExpectedErrorCodes: []string{"backend.decimal.scale_invalid"}},
		},
		Sources: []capabilitycontract.CapabilityAuthoringSource{
			{Kind: "contract", Path: "runtime/domain/appschema/contract/appschema_field_authoring.go", Symbol: "ApplicationSchemaFieldAuthoringCapability"},
			{Kind: "validation", Path: "runtime/domain/appschema/validation/appschema_field_mutation_validation.go", Symbol: "ApplicationSchemaNormalizeFieldMutation"},
			{Kind: "service", Path: "runtime/application/appschema/appschema_definition_validation_application_service.go", Symbol: "ApplicationSchemaApplicationService.ValidateApplicationDefinitionPayload"},
		},
	}
}
