package scheduler

import (
	principalmodel "github.com/domainry/domainry-runtime/runtime/domain/principal/model"

	"context"
	"strings"
	"time"

	reportmodel "github.com/domainry/domainry-report-sdk/model"
	recordmodel "github.com/domainry/domainry-runtime/runtime/domain/record/model"
	schedulerpolicy "github.com/domainry/domainry-runtime/runtime/domain/scheduler/policy"
)

type ReportSnapshotRuntime interface {
	RefreshSnapshot(context.Context, string, string, principalmodel.Principal) (reportmodel.ReportSnapshot, error)
}

func (s *SchedulerApplicationService) schedulerProcessReportSnapshotDefinition(ctx context.Context, workspaceID string, definition, run recordmodel.Record, principal principalmodel.Principal) ([]schedulerBusinessEvidence, error) {
	if s.reportSnapshots == nil {
		return nil, badRequest("backend.scheduler.report_snapshot_runtime_unavailable", "target_type", "report_snapshot_refresh")
	}
	principal.WorkspaceID = workspaceID
	idempotencyKey := strings.TrimSpace(existingStringBefore(run, "idempotency_key"))
	if idempotencyKey == "" {
		idempotencyKey = run.ID
	}
	snapshot, err := s.reportSnapshots.RefreshSnapshot(ctx, strings.TrimSpace(existingStringBefore(definition, "target_key")), idempotencyKey, principal)
	if err != nil {
		return nil, err
	}
	return []schedulerBusinessEvidence{{Kind: "report_snapshot_refreshed", ObjectKey: "report_snapshot", RecordID: snapshot.ID}}, nil
}

type schedulerBusinessEvidence struct {
	Kind      string
	ObjectKey string
	RecordID  string
}

func (s *SchedulerApplicationService) schedulerProcessReportExportDefinition(ctx context.Context, workspaceID string, definition recordmodel.Record, run recordmodel.Record, now time.Time) ([]schedulerBusinessEvidence, error) {
	targetKey := valueOrDefault(existingStringBefore(definition, "target_key"), "scheduled_report_export")
	reportDefinition, err := s.schedulerEnsureReportDefinition(ctx, workspaceID, targetKey, now)
	if err != nil {
		return nil, err
	}
	queryRun, err := s.schedulerInsertRecordIfMissing(ctx, workspaceID, "report_query_run", "sched_rq_"+schedulerpolicy.SchedulerSlug(run.ID), now, map[string]any{
		"query_number":        "RQ-" + schedulerpolicy.SchedulerSlug(run.ID),
		"query_status":        "completed",
		"status":              "completed",
		"report_definition":   reportDefinition.ID,
		"requested_by":        "workflow:worker",
		"result_count":        0,
		"source_record_count": 0,
	})
	if err != nil {
		return nil, err
	}
	exportAudit, err := s.schedulerInsertRecordIfMissing(ctx, workspaceID, "report_export_audit", "sched_exp_"+schedulerpolicy.SchedulerSlug(run.ID), now, map[string]any{
		"export_number":     "EXP-" + schedulerpolicy.SchedulerSlug(run.ID),
		"export_status":     "completed",
		"status":            "completed",
		"approval_result":   "not_required",
		"report_definition": reportDefinition.ID,
		"report_query_run":  queryRun.ID,
		"row_count":         0,
		"watermark_text":    "Generated by scheduler " + run.ID,
	})
	if err != nil {
		return nil, err
	}
	downloadTask, err := s.schedulerInsertRecordIfMissing(ctx, workspaceID, "download_task", "sched_dl_"+schedulerpolicy.SchedulerSlug(run.ID), now, map[string]any{
		"task_name":           "Download " + targetKey,
		"download_status":     "ready",
		"status":              "ready",
		"token_status":        "active",
		"virus_scan_status":   "passed",
		"file_format":         "csv",
		"file_name":           targetKey + "-" + now.Format("20060102") + ".csv",
		"report_export_audit": exportAudit.ID,
	})
	if err != nil {
		return nil, err
	}
	return []schedulerBusinessEvidence{
		{Kind: "report_query_run_created", ObjectKey: "report_query_run", RecordID: queryRun.ID},
		{Kind: "report_export_audit_created", ObjectKey: "report_export_audit", RecordID: exportAudit.ID},
		{Kind: "download_task_created", ObjectKey: "download_task", RecordID: downloadTask.ID},
	}, nil
}

func (s *SchedulerApplicationService) schedulerEnsureReportDefinition(ctx context.Context, workspaceID, targetKey string, now time.Time) (recordmodel.Record, error) {
	recordID := "sched_report_" + schedulerpolicy.SchedulerSlug(targetKey)
	return s.schedulerInsertRecordIfMissing(ctx, workspaceID, "report_definition", recordID, now, map[string]any{
		"name":               "Scheduled " + targetKey,
		"report_code":        targetKey,
		"status":             "active",
		"business_domain":    "scheduler",
		"default_time_grain": "day",
		"date_filter_label":  "scheduled_at",
		"owner":              "workflow:worker",
	})
}

func (s *SchedulerApplicationService) schedulerInsertRecordIfMissing(ctx context.Context, workspaceID, objectKey string, recordID string, now time.Time, data map[string]any) (recordmodel.Record, error) {
	object, ok := schemaObjectMap(s.schema.SchemaForPrincipal(ctx, principalmodel.Principal{}).Objects)[objectKey]
	if !ok {
		return recordmodel.Record{}, badRequest("backend.scheduler.target_object_missing", "object", objectKey)
	}
	if existing, ok, err := s.repository.GetRecord(ctx, workspaceID, object, recordID); err != nil {
		return recordmodel.Record{}, internalError("get scheduler domain evidence", err)
	} else if ok {
		return existing, nil
	}
	record := recordmodel.Record{
		ID:        recordID,
		CreatedAt: now.Format(time.RFC3339),
		UpdatedAt: now.Format(time.RFC3339),
		Data:      data,
	}
	if err := s.insertRecord(ctx, workspaceID, object, record, "scheduler report evidence"); err != nil {
		return recordmodel.Record{}, err
	}
	return record, nil
}
